### ISSUE TITLE
Does not declare any runtime dependencies

### ISSUE THREAD

**Issue by robross0606** [JamieMason/expect-more#56]
## Description

This project only declares `devDependencies` which is not really accurate.  `devDependencies` are not transitory which means there is not currently any declared version compatibility limitation with respect to Jest and this project when used together in another project.  However, this project breaks with `jest` and `jest-jasmine2` ^28:
```
    Cannot find module 'expect/build/jasmineUtils' from 'node_modules/expect-more-jest/dist/to-be-array-of.js'

    Require stack:
      node_modules/expect-more-jest/dist/to-be-array-of.js
      node_modules/expect-more-jest/dist/index.js

      at Resolver._throwModNotFoundError (node_modules/jest-runtime/node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (node_modules/expect-more-jest/dist/to-be-array-of.js:5:22)
```

## Suggested Solution

This project should be declaring regular runtime dependencies or peer dependencies for any version requirements it needs to run.  Otherwise, users of this library are not alerted that this library even requires `jest` let alone that it only works with certain versions.

**Comment by JamieMason** [comment]
good spot, thanks 👍🏻

**Comment by JamieMason** [comment]
Thanks @robross0606, the `expect/build/jasmineUtils` issue should hopefully now be fixed in [expect-more-jest@5.4.1](https://github.com/JamieMason/expect-more/releases/tag/expect-more-jest%405.4.1).

On dependencies, `expect-more-jest` defines its runtime dependencies at: https://github.com/JamieMason/expect-more/blob/1289cfb4193bf1eac57e7762a37dda8b1dd0c0fc/packages/expect-more-jest/package.json#L10-L14

Something I'm not completely sure about that you can maybe help with – the package being depended on was `expect` rather than `jest` and that was defined in `dependencies` – but it still broke. `jest` depends on this too and maybe it won out(?) I'm not entirely sure.

Diff: https://github.com/JamieMason/expect-more/commit/3ebb2523f8b5f7bd879bc529be493b49de6ef120#diff-7d360743c6462dda3f5045aae1eb86d4a140e9f709033fa04fab9d4a980547da

**Comment by robross0606** [comment]
I'd have to compare the versions of `jest` too to be sure.  The real question is whether your true dependency was on `expect` or was on `expect-utils`.  If you make calls that rely on a specific version of `expect-utils` then you need to declare that, regardless of whether you're declaring `expect` too.  It is entirely possible that `expect-utils` could make a breaking change to their API while still using the same version of `expect`.  I'm not well versed enough in how `jest` sets up all its packages to know for sure how the transitive dependencies were shaking out.

**Comment by JamieMason** [comment]
I think this can be closed.
